### ISSUE TITLE
PCB improvements for AskSinAnalyzer

### ISSUE THREAD

**Issue by stan23** [stan23/myPCBs#1]
This is a rough list in case there will be a future update of the PCB.

- make sure the extra description of the jumpers and connectors is printed on the PCB
- list the meaning of the DIP switches
- place a FT232
- wire RX/TX to the FTDI
- use a switch to mux between ATmega and ESP
- optional reset button for ESP

**Comment by stan23** [comment]
see https://github.com/espressif/esptool/wiki/ESP32-Boot-Mode-Selection#automatic-bootloader

**Comment by stan23** [comment]
see https://ecksteinimg.de/Datasheet/HL01005/MatrixCoreV2%20Schematic.pdf

**Comment by TomMajor** [comment]
You left power pins 3 and 6 at TQFP32 unconnected, this is not good.

All Vcc and Gnd pins should be connected.
This is common design/layout practice because the user does not know if the chip die has multiple power pads and how they are bonded inside the chip housing.

Ref:
https://www.avrfreaks.net/comment/1063221#comment-1063221
https://electronics.stackexchange.com/questions/231343/component-with-multiple-vcc-and-gnd-pins-should-i-connect-all-of-them
https://www.avrfreaks.net/comment/1394356#comment-1394356

**Comment by stan23** [comment]
You're right!
Wtf, they do not show up on the device at all.

**Comment by TomMajor** [comment]
Another weird thing, pin 21 in Layout is connected to Gnd, which is correct, but this connection is not shown in the schematics, or did I miss it?
There should be no difference between schematics and layout in terms of connections.

**Comment by stan23** [comment]
I'll go back to the old device symbol, which has all supply pins explicitly shown.

**Comment by stan23** [comment]
I accidentally picked the ATmega328PB which has less supply pins :(

**Comment by TomMajor** [comment]
good point, did not know this.
(never designed for mega328PB, would have assumed same pinning as P type, which is obviously wrong :crying_cat_face:  )

**Comment by stan23** [comment]
closed by 0836a9e2e8393039dbb52a037b12d36954bc585e
